/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_cm4(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTA0 (coord B10), BUTTON_NMI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE8 (coord P16), BUTTON_LLWUP23
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW3_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW3_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW3_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE9 (coord N16), BUTTON_LLWUP24
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW4_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW4_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW4_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW4_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW4_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW4_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE12 (coord L12), BUTTON_LLWUP26
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW5_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW5_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW5_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW5_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW5_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW5_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtons(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTA22 (coord B6), Q6[2]/LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_RGB_BLUE_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_RGB_BLUE_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_RGB_BLUE_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_RGB_BLUE_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_RGB_BLUE_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA23 (coord E6), Q7[5]/LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_RGB_GREEN_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_RGB_GREEN_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_RGB_GREEN_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_RGB_GREEN_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_RGB_GREEN_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTA24 (coord D6), Q7[2]/LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDS_RGB_RED_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDS_RGB_RED_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDS_RGB_RED_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDS_RGB_RED_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDS_RGB_RED_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTC8 (coord P3), U11[1]/K32L_UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_TX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_TX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name PORTC7 (coord N2), U40[1]/K32L_UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_RX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG_UART0_RX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void); /* Function assigned for the Cortex-M4F */

/*! @name EXTAL32 (coord E16), Y1[1]/EXTAL_32KHZ
  @{ */
/* @} */

/*! @name XTAL32 (coord E17), Y1[2]/XTAL_32KHZ
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSC(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTE30 (coord G17), U14[4]/ACCEL_I2C3_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCEL_ACCEL_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_SCL_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITACCEL_ACCEL_SCL_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTE29 (coord G15), U14[6]/ACCEL_I2C3_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCEL_ACCEL_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_SDA_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITACCEL_ACCEL_SDA_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTE1 (coord R16), U14[11]/ACCEL_INT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITACCEL_ACCEL_INT1_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCEL_ACCEL_INT1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITACCEL_ACCEL_INT1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTE22 (coord J16), U14[9]/ACCEL_INT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITACCEL_ACCEL_INT2_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT2_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCEL_ACCEL_INT2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_INT2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITACCEL_ACCEL_INT2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTE27 (coord H14), U14[16]/ACCEL_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITACCEL_ACCEL_RST_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_RST_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_RST_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCEL_ACCEL_RST_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCEL_ACCEL_RST_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITACCEL_ACCEL_RST_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCEL(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTB9 (coord F4), J4[6]/J47[2]/ARDUINO_A2/ADC0_SE3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLIGHT_SENSOR_SNS_LIGHT_ADC_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLIGHT_SENSOR_SNS_LIGHT_ADC_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLIGHT_SENSOR_SNS_LIGHT_ADC_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLIGHT_SENSOR_SNS_LIGHT_ADC_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITLIGHT_SENSOR_SNS_LIGHT_ADC_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLIGHT_SENSOR(void); /* Function assigned for the Cortex-M4F */

/*! @name USB0_DM (coord T12), J8[2]/K32L_USB_DN
  @{ */
/* @} */

/*! @name USB0_DP (coord T11), J8[3]/K32L_USB_DP
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSB(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTD11 (coord R11), J9[P1]/SDHC0_D2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_D2_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_D2_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_D2_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD10 (coord P11), J9[P2]/SDHC0_D3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_D3_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_D3_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_D3_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD9 (coord U11), J9[P3]/SDHC0_CMD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_CMD_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_CMD_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_CMD_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD8 (coord T9), J9[P5]/SDHC0_DCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_DCLK_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_DCLK_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_DCLK_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTD7 (coord P10), J9[P7]/SDHC0_D0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_D0_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_D0_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_D0_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD6 (coord U9), J9[P8]/SDHC0_D1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SDHC0_D1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SDHC0_D1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SDHC0_D1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC27 (coord P6), J9[G1]/SD_DETECT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITSDHC_SD_DETECT_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITSDHC_SD_DETECT_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITSDHC_SD_DETECT_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSDHC_SD_DETECT_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITSDHC_SD_DETECT_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDHC(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTA26 (coord A5), J1[4]/ARDUINO_D1_UART1_TX/UART1_TX_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_TX_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_TX_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_TX_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                                            /* @} */

/*! @name PORTA25 (coord B5), J1[2]/ARDUINO_D0_UART1_RX/UART1_RX_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_RX_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_RX_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_UART_ARDUINO_LPUART1_RX_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitARDUINO_UART(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTB6 (coord E1), J2[6]/ARDUINO_D10/SPI0_PCS2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SSN_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SSN_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SSN_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SSN_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SSN_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name PORTB5 (coord D2), J2[8]/ARDUINO_D11/SPI0_SOUT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MOSI_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MOSI_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MOSI_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORTB7 (coord E2), J2[10]/ARDUINO_D12/SPI0_SIN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MISO_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MISO_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_MISO_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORTB4 (coord C2), J2[12]/ARDUINO_D13/SPI0_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SCK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SCK_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITARDUINO_SPI_ARDUINO_SPI_SCK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitARDUINO_SPI(void); /* Function assigned for the Cortex-M4F */

/*! @name PORTB3 (coord C1), J2[4]/ARDUINO_D9/PWM
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ARDUINO_PTB3_ARDUINO_PTB3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_PTB3_ARDUINO_PTB3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_PTB3_ARDUINO_PTB3_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_PTB3_ARDUINO_PTB3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_PTB3_ARDUINO_PTB3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Arduino_PTB3(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
