/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 23/09/2021 14:18:05
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            24000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     170000000
#define MX_HCLKFreq_Value                       170000000
#define MX_FCLKCortexFreq_Value                 170000000
#define MX_CortexFreq_Value                     170000000
#define MX_AHBFreq_Value                        170000000
#define MX_APB1Freq_Value                       170000000
#define MX_APB2Freq_Value                       170000000
#define MX_APB1TimFreq_Value                    170000000
#define MX_APB2TimFreq_Value                    170000000
#define MX_ADC12Freq_Value                      170000000
#define MX_LPUART1Freq_Value                    170000000
#define MX_I2C1Freq_Value                       170000000
#define MX_I2SFreq_Value                        170000000
#define MX_USART1Freq_Value                     170000000
#define MX_USART2Freq_Value                     170000000
#define MX_USART3Freq_Value                     170000000
#define MX_FDCANFreq_Value                      170000000
#define MX_LPTIM1Freq_Value                     170000000
#define MX_QSPIFreq_Value                       170000000
#define MX_SAI1Freq_Value                       170000000
#define MX_PWRFreq_Value                        170000000
#define MX_RTCFreq_Value                        32768
#define MX_USBFreq_Value                        170000000
#define MX_WatchDogFreq_Value                   32000
#define MX_CECFreq_Value                        4000000
#define MX_HRTIM1Freq_Value                     170000000
#define MX_MCO1PinFreq_Value                    16000000

/*-------------------------------- LPUART1    --------------------------------*/

#define MX_LPUART1                              1

/* GPIO Configuration */

/* Pin PA3 */
#define MX_LPUART1_RX_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Pin                       PA3
#define MX_LPUART1_RX_GPIOx                     GPIOA
#define MX_LPUART1_RX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_RX_STLINKV3E_VCP_TX          LPUART1_RX
#define MX_LPUART1_RX_GPIO_Pin                  GPIO_PIN_3
#define MX_LPUART1_RX_GPIO_AF                   GPIO_AF12_LPUART1
#define MX_LPUART1_RX_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_LPUART1_TX_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Pin                       PA2
#define MX_LPUART1_TX_GPIOx                     GPIOA
#define MX_LPUART1_TX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_TX_STLINKV3E_VCP_RX          LPUART1_TX
#define MX_LPUART1_TX_GPIO_Pin                  GPIO_PIN_2
#define MX_LPUART1_TX_GPIO_AF                   GPIO_AF12_LPUART1
#define MX_LPUART1_TX_GPIO_Mode                 GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13
#define MX_T_SWDIO                              SYS_JTMS_SWDIO

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14
#define MX_T_SWCLK                              SYS_JTCK_SWCLK

/* Pin PB3 */
#define MX_SYS_JTDO_SWO_Pin                     PB3
#define MX_T_SWO                                SYS_JTDO_SWO

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_B1_blue_push_button                  PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultEXTI            GPIO_MODE_IT_RISING

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LD2_green_led                        PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC7 */
#define MX_PC7_Pin                              PC7
#define MX_PC7_GPIOx                            GPIOC
#define MX_PC7_GPIO_PuPd                        GPIO_NOPULL
#define MX_ARDUINO_IO_D9                        PC7
#define MX_PC7_GPIO_Pin                         GPIO_PIN_7
#define MX_PC7_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB6 */
#define MX_PB6_GPIO_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PB6_GPIO_FM6                         __NULL
#define MX_PB6_Pin                              PB6
#define MX_PB6_GPIOx                            GPIOB
#define MX_PB6_PinState                         GPIO_PIN_SET
#define MX_PB6_GPIO_PuPd                        GPIO_NOPULL
#define MX_ARDUINO_IO_D10                       PB6
#define MX_PB6_GPIO_Pin                         GPIO_PIN_6
#define MX_PB6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

